disabled_rules:
  - trailing_whitespace # 余分に改行がある方が視認性が上がる為、無効
  - type_name # クラス名は長くして情報を詰めておく必要もある為、無効
  - valid_docs
  # ルール一覧を表示
  #- colon
  #- control_statement
  #- file_length
  #- force_cast
  #- function_body_length
  #- leading_whitespace
  #- line_length
  #- nesting
  #- operator_whitespace
  #- return_arrow_whitespace
  #- todo
  #- trailing_newline
  #- variable_name_max_length
  #- variable_name_min_length
  #- type_body_length
  #- variable_name

line_length: 200

excluded: # Lint対象から外すファイルのあるパスを記述
  - Pods
  - Tests

# クラスの行数
type_body_length:
  - 100 # warning
  - 200 # error

# 変数名の最大文字数
variable_name_max_length:
  - 10 # warning
  - 20 # error

# 変数名の最小文字数
variable_name_min_length:
  - 1 # warning
  - 0 # error

# 関数の長さ
function_body_length:
  - 20 # warning
  - 40 # error
